apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: voco
  namespace: voco
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: voco-backend
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: voco-frontend
                port:
                  number: 80

