apiVersion: v1
kind: Service
metadata:
  name: voco-frontend
  namespace: voco
spec:
  selector:
    app: voco-frontend
  ports:
    - name: http
      port: 80
      targetPort: http
  type: ClusterIP

