apiVersion: v1
kind: Service
metadata:
  name: livekit-svc
  namespace: voco
spec:
  selector:
    app: livekit
  type: ClusterIP
  ports:
    - name: signaling
      port: 7880
      targetPort: signaling
      protocol: TCP
    - name: rtc-tcp
      port: 7881
      targetPort: rtc-tcp
      protocol: TCP

