apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: voco

resources:
  - base/namespace.yaml
  - base/frontend/deployment.yaml
  - base/frontend/service.yaml
  - base/backend/deployment.yaml
  - base/backend/service.yaml
  - base/livekit/deployment.yaml
  - base/livekit/service.yaml
  - base/ingress.yaml
  - ingress-livekit-wss.yaml
  - backend-configmap.yaml
  - livekit-configmap.yaml

patches:
  - path: patch-backend-env.yaml
  - path: patch-livekit-service-nodeport.yaml
  - path: patch-livekit-service-udp-nodeport.yaml
